### ISSUE TITLE
Girens not saving login information.

### ISSUE THREAD

**Issue by lineber** [flathub/nl.g4d.Girens#7]
Each time I enter Girens (fresh flatpak), I have to logout from server and then login with the ip and token. When I close the app, data hasn't been saved.

Also there are missing icons in the top left side.

-Jerry

**Comment by tijder** [comment]
Thanks for creating an issue for this. I tried to reproduce this issue, but for me it's working fine. Maybe the problem occurs because the app can't access your server yet. When the app can't access the server it will go to the login screen. Can you look in the file "~/.var/app/nl.g4d.Girens/config/config" and check if the login info is correct?

**Comment by lineber** [comment]
Correction, the data is saved in the file "~/.var/app/nl.g4d.Girens/config/config" but does not re-login to the session when starting the program.

**Comment by lineber** [comment]
The file has the information, but some setting is not allowing it to re-login. It sounds like it is just something I did. I ran this flatpak at one point and it worked perfectly, just not anymore.
